
http { 
    server_tokens off;

    log_format minimal '$remote_addr "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';

    map $status $log_errors {
        default 0;
        ~^(4|5) 1; 
    }
    include /etc/nginx/sites_conf/*.conf;
}