name: CI/CD Pipeline

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build
        run: bun run build

      - name: Deploy Static Files
        uses: appleboy/scp-action@v1.0.6
        with:
          host: ${{ secrets.VPS_HOST }}
          source: "dist/*"
          target: "/opt/nginx/sites/portfolio/"
          strip_components: 1

      - name: Deploy Config
        uses: appleboy/scp-action@v1.0.6
        with:
          host: ${{ secrets.VPS_HOST }}
          source: "nginx.conf"
          target: "/opt/nginx/sites_conf/"

      - name: Deploy Snippets
        uses: appleboy/scp-action@v1.0.6
        with:
          host: ${{ secrets.VPS_HOST }}
          source: "snippets/csp_portfolio.conf"
          target: "/opt/nginx/snippets/"
          strip_components: 1
